### ISSUE TITLE
S3 prefix

### ISSUE THREAD

**Issue by mirkods** [awslabs/aws-data-lake-solution#23] opened 2019-02-05 15:03 UTC
Hi there,

is there a way to change the s3 packages prefix? I'd like to avoid to save packages in the bucket root but for example add them in a packages/ prefix.

Any suggestions?

**Comment by hvital** [comment] 2019-02-05 19:23
Hi @mirkods 

Probably the fastest way to address this is upload the files to S3 using your own bucket structure and then import the files (you can refer just the bucket_name, folder path of filename) via manifest file. More info: http://docs.awssolutionsbuilder.com.s3-website-us-east-1.amazonaws.com/data-lake/user-guide/working-with-packages/#using-manifest-files

Does this answer your question?

Regards,

**Comment by knihit** [comment] 2019-12-19 21:40
Hi @mirkods, please advise if the issue is resolved. If you have more questions please feel free to reach out. If not, can we close this issue.

**Closed** 2020-02-13 23:45 UTC
